name: Sonar
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Build with npm
        run: |
          npm ci
          npm run build --if-present
          npm test
          npm run coverage
      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
        with:
          args: >
            -Dsonar.sources=./lib -Dsonar.tests=./test
            -Dsonar.coverage.jacoco.xmlReportPaths=test-results.xml
            -Dsonar.javascript.lcov.reportPaths=.nyc_output/coverage.lcov
